

exclude:
  - "strings.dart"

analyzer:
  strong-mode:
    implicit-dynamic: true
    implicit-casts: true
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
  enable-experiment:
    - extension-methods

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - annotate_overrides
    #- avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - directives_ordering
    - empty_catches
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    #- non_constant_identifier_names
    - only_throw_errors
    - overridden_fields
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_final_fields
    #- prefer_final_locals
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    #- unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps